# Setup
title:        The musings of bluz71
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       bluz71
  url:        https://bluz71.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-feed

#Others
markdown: kramdown
